### ISSUE TITLE
Exploration loss question

### ISSUE THREAD

**Issue by Denys88** [alex-petrenko/sample-factory#113]
I see you have two options for the exploration loss:
symmetric_kl_with_uniform_prior and entropy. And you used symmetric KL as the loss in the vizdoom config.
Is there any paper or comparison between both approaches?

**Comment by alex-petrenko** [comment]
Hi @Denys88 !
Not really. This was something I came up with while working on Sample Factory for discrete action distributions, and it didn't end up in the paper, mainly because I could not find reliable evidence that it is significantly better for performance (at least on the tasks we tested)

The inspiration comes from behavior cloning, for example: https://blog.aqnichol.com/2019/04/03/prierarchy-implicit-hierarchies/
Many behavior cloning algorithms will minimize some KL-loss with the prior (teacher), but this blog post considers it in the context of regular end-to-end learning.

Basically, KL-divergence with a prior is a more general version of entropy loss. Theoretically, KL-divergence with a uniform prior is exactly equivalent to entropy loss, so if your prior is a uniform distribution, they just serve the same purpose. But KL-divergence also allows you to use any other prior. I.e. if you know that an optimal policy would use a certain action very infrequently, you can choose a non-uniform prior to reflect that.

In Sample Factory I used **Symmetric** KL divergence because regular KL (or entropy) penalty will be still relatively small even when policy entropy approaches zero. Sometimes this happens in practice - a policy would just collapse to zero entropy to exploit some local optimum. Symmetric KL-divergence will approach infinity if the policy entropy approaches zero, creating a much stronger signal that prevents such a collapse. I found that it generally works well in practice across a wide range of discrete-action tasks, and I have never seen a 0-entropy collapse since I added it.

**Comment by alex-petrenko** [comment]
Now that I think about it, might be a good idea to write a little blog post.

**Comment by Denys88** [comment]
Thanks for the answer, want to try this idea. One thing which concerns me is the scale of the symmetric KL so you need to apply smaller coefficient and it is hard to find the best hyper parameters for the both cases.

**Comment by alex-petrenko** [comment]
That's fair.
I remember values between 0.001 and 0.005 were the most robust for discrete-action tasks. 
Obviously, this whole thing does not apply to continuous-action tasks, and for them, you need different loss coefficients too.
