### ISSUE TITLE
Question about Multi-Agent Environments

### ISSUE THREAD

**Issue by KonstantinRamthun** [alex-petrenko/sample-factory#119]
Hi!

I've got a brief question about multi-agent environments. Does sample-factory support multi-agent environments with asymmetric agents?

**Comment by alex-petrenko** [comment]
If by that you mean entirely different agent architectures or action spaces, then the answer currently is no.
The main component that prevents that is the allocator of shared memory buffers - it currently assumes that all policies have the same input (observation) and output (actions) shape.

If we allocate the shared memory for trajectories per-policy, it should be possible to have heterogeneous agents.

It would also require some extra configuration to specify models and data shapes for each policy.

What is the task in question, if it's not a secret?

**Comment by KonstantinRamthun** [comment]
That's exactly what i mean. Thank you for your quick response. 

I'm part of the project group 642 of the faculty of computer science at TU Dortmund. We are using a [fork of sample-factory](https://github.com/PG642/multi-sample-factory) to train agents for the game rocket league. To enable training on a HPC, we are reverse engineering rocket league and developing a set of environments in Unity with [ml-agents](https://github.com/Unity-Technologies/ml-agents), which we call [Robo League](https://github.com/PG642/RoboLeague). ml-agents environments support asymmetric agents, so the obvious idea was to transfer this capability into sample-factory, but actually we do not have any environment with asymmetric agents right now. If we end up needing this capability and implementing anything for it, we will of course create a PR here for you to use it.

**Comment by alex-petrenko** [comment]
Sounds awesome! Good luck with your project!

**Comment by KonstantinRamthun** [comment]
Thank you!

I have another question regarding multi-agent scenarios: What's the purpose of the parameter `--num-policies`? I think you only set it when you have an environment with multiple agents, so I think you use it to train different versions of the same policy and each policy is fed by a different agent in each episode. At the end you then select the policy, which performs best. Wouldn't it be more beneficial to use the samples of all agents and train one policy instead? E.g. in a rocket league 1-vs-1 match, we have two agents with the same policy. So we could use 2 samples from one environment step to get a full batch in approximately half of the time (in comparison to the time we would need with only one agent).

**Comment by alex-petrenko** [comment]
Your point is correct of course, yet --num-policies has multiple uses.

1. Main intended use is in conjunction with PBT (population-based training). --with_pbt=True. Here this parameter would just specify the number of policies in a population. There is a lot of literature about benefits of PBT, it enables better exploration and leads to more robust policies since each policy in multi-agent setup is trained against a variety of opponents. Examples are DeepMind CTF or AlphaStar. My doom duel policies were also trained with PBT. 
2. In multi-agent training even without PBT you can benefit from training multiple independent policies, again just because it is not purely self-play, but you play against different opponents (including self)
3. You can use --num_policies if you want to train policies initialized from several seeds, even without multi-agent learning. But this is more or less equivalent to running N independent experiments in parallel, so only moderately useful.

**Comment by KonstantinRamthun** [comment]
Thank you for this detailed answer!
