### ISSUE TITLE
Are pretrained weights available?

### ISSUE THREAD

**Issue by snailrowen1337** [alex-petrenko/sample-factory#121]
Are there any pretrained weights available? I'd love to try the code base without having to train an agent from scratch. Thanks!

**Comment by alex-petrenko** [comment]
Hi @snailrowen1337! 

I might have some trained agents for single-agent Doom environments such as Battle (labyrinth with monsters in the Gif animation). Would that be helpful?

Other older training runs that I have might not be that useful because they are not compatible with the latest version of the code (names of tensors in the computation graph changed).

**Comment by snailrowen1337** [comment]
That would be great, thanks!!

**Comment by alex-petrenko** [comment]
See here: https://github.com/alex-petrenko/sample-factory/tree/master/trained_policies 
Please let me know if you have any questions!

**Comment by snailrowen1337** [comment]
That's just what I was looking for, thanks!
