### ISSUE TITLE
Advice for Sample Factory use?

### ISSUE THREAD

**Issue by bycn** [alex-petrenko/sample-factory#122]
Hi Alex, this is very impressive work! 
My use case is for an environment where 
- each env requires its own process
- on a 16 core machine, maximum sample throughput is reached at a small amount (~40) of environments due to poor cache usage   (comes w/ the env)
- but env is fast, sample throughput bottlenecked by policy inference speed, not the simulation/step itself

Some requirements for training are that 
- Self play which plays against various older versions of the agent 20% of the time 
- 1 GPU is probably fine for learning

Given these characteristics, I theorized I may be better suited to roll my own setup for the sampler where rollout & policy workers are combined, so that each rollout worker has a copy of the policy. Self play details are not too difficult, i.e., periodically save a copy of the params to a local directory, and reserve a few workers to play vs these older versions.

Do you have any thoughts/advice on the right approach to this case? Thank you! (Feel free to ask for any clarifications)

**Comment by bycn** [comment]
Also — I noticed that you created this issue in the past https://github.com/ray-project/ray/issues/5278 and I'm curious what adjustments were key in this implementation to get PPO with LSTMs to work

**Comment by alex-petrenko** [comment]
@bycn as for LSTMs in RLLIB, I never really got it to work. Sample Factory uses an implementation which handles episode resets in the middle of the trajectory quite differently. Whether this affects learning performance is not clear, but with SF I always had much more stable training than RLLIB. 
Then again, it might have changed in the last 1-2 years.

Regarding your setup:
 * `each env requires its own process` - this should be easy to do, you just set `--worker_num_splits=1` to disable double-buffered sampling, and `--num_envs_per_worker=1` to have one env per process. Alternatively, you can make a wrapper around your env that spawns a separate process for an env instance and communicates with a rollout worker through IPC (much like we do for multiplayer Doom envs). Then you can have several of these wrapped envs per worked and be able to benefit from double-buffered sampling, although IPC may kill the benefits from it.
 *  `on a 16 core machine, maximum sample throughput is reached at a small amount (~40) of environments due to poor cache usage (comes w/ the env)` - I think if you run each env in a separate process you will not benefit from using significantly more processes than you have cores. I usually do one worker per logical CPU core (so 16 or 32 in your case).
 * `Self play which plays against various older versions of the agent 20% of the time` this is something you will need to implement. SF supports training a population of agents that all play against each other in all sorts of ways. The logic for choosing policies in a single env is controlled by policy_manager.py (you can customize that). Adding old policies to the mix requires custom logic, but I found that having a population of policies also works well (kinda serves a similar purpose).
 * ` that each rollout worker has a copy of the policy` - if you're bottlenecked by policy inference time I'd advise against that. Policy worker will batch your inference requests together and execute them at once on the GPU, increasing the overall throughput. If you use multiple inference workers, each one will have to work with very small batches (or batch size 1) which will hurt throughput significantly.
 * `periodically save a copy of the params to a local directory, and reserve a few workers to play vs these older versions.` this sounds about right! If you manage to implement this as a PR, I'd be happy to help you with merge etc.

**Comment by bycn** [comment]
Thanks for the detailed answer, appreciate it! It makes sense to me to use sample factory then. I'll give it a shot soon 👍 One detail I forgot to mention is that we train without any resets — are there changes or even optimizations I should make based on this or just avoiding returning `done` is sufficient?

**Comment by alex-petrenko** [comment]
From the learning point of view, it is fine. 
But it might mess up some logic that relies on counting episodes. Namely:
1) calculating per-episode rewards and other metrics (this obviously won't be happening since episodes are infinite)
2) policy manager currently re-samples the agent-to-policy mapping only at the beginning of the episode. This might still be okay with a sufficient number of workers (you will get enough mix-and-match randomness from the initial sampling)
3) PBT I think won't update reward shaping schemes if you never reset episodes. But you're likely not using this feature (gotta inherit your env from RewardShapingInterface)

There might be other smaller things, but I suggest you try and see if it works. If there's something important relying on resets, consider making an artificial reset() every 10 minutes or something!
