### ISSUE TITLE
How to use all cores?

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#123]
Can't utilize all 16 logical processors (8 cores, 2 threads) on an AMD Ryzen laptop (AMD GPU :( ). I can see that at any point 8 processors are maxed, while the other 8 vary between 0 and 50%. Tried various `num_workers` values between 2 and 16 as well as various `policy_workers_per_policy`. Any suggestions on how are welcome.

Command: 
`python -m sample_factory_examples.train_gym_env --algo=APPO --use_rnn=False --recurrence=1 --with_vtrace=False --batch_size=512 --hidden_size=256 --encoder_type=mlp --encoder_subtype=mlp_mujoco --reward_scale=0.1 --save_every_sec=10 --experiment_summaries_interval=20 --experiment=example_gym_cartpole-v1 --env=gym_CartPole-v1 --device=cpu  --num_envs_per_worker=2 --num_workers=7 --train_in_background_thread=true --policy_workers_per_policy=4`

**Comment by alex-petrenko** [comment]
If you have 16 logical processes, I recommend using 16 workers (--num_workers=16). Increase --num_envs_per_worker to something like 8 or 16 so that you process your policy requests in bigger batches and the workers spend less time waiting.
I never really experimented much with CPU training. So not sure how much it helps to have several policy workers per policy.
You will end up with more parallel processes each doing less work (inference with small batches), which can potentially increase communication overhead. But keep it if it helps!

**Comment by jarlva** [comment]
Thanks @alex-petrenko . My issue was setting the correct number of cores in the .wslconfig file (running in WSL2 under windows).
