### ISSUE TITLE
PackedSequence should be unpacked first before any chunk manipulations

### ISSUE THREAD

**Issue by mehanicum** [alex-petrenko/sample-factory#124]
sample factory uses PackedSequence in case of RNN . When actor and critic don't share the weights, it's needed to split the head output as well as RNN states into chunks:
```   
def _core_rnn(self, head_output, rnn_states):
        """
        This is actually pretty slow due to all these split and cat operations.
        Consider using shared weights when training RNN policies.
        """

        num_cores = len(self.cores)
        head_outputs_split = head_output.chunk(num_cores, dim=1)
        rnn_states_split = rnn_states.chunk(num_cores, dim=1)

```

head_output and rnn_states are PackedSequence instead of numpy/array and it causes the exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sample_factory/algorithms/appo/learner.py", line 1156, in _train_loop
    self._process_training_data(data, timing, wait_stats)
  File "/usr/local/lib/python3.7/dist-packages/sample_factory/algorithms/appo/learner.py", line 1106, in _process_training_data
    train_stats = self._train(buffer, batch_size, experience_size, timing)
  File "/usr/local/lib/python3.7/dist-packages/sample_factory/algorithms/appo/learner.py", line 737, in _train
    core_output_seq, _ = self.actor_critic.forward_core(head_output_seq, rnn_states)
  File "/usr/local/lib/python3.7/dist-packages/sample_factory/algorithms/appo/model.py", line 175, in forward_core
    return self.core_func(head_output, rnn_states)
  File "/usr/local/lib/python3.7/dist-packages/sample_factory/algorithms/appo/model.py", line 147, in _core_rnn
    head_outputs_split = head_output.chunk(num_cores, dim=1)
AttributeError: 'PackedSequence' object has no attribute 'chunk'

**Comment by alex-petrenko** [comment]
Fair enough! I guess I never really used split models with RNNs after we introduced this optimization.
Thank you for pointing out!

I'm trying to work on a major update of SF (possibly, SF 2.0), and maybe it makes sense to address this after a bulk of changes. But let me know if this is mission critical, in this case I can take a look earlier!

Any particular considerations regarding using separate weights with RNNs? I can see arguments for either, but in practice I always found that shared weights work a little bit better: I guess the supervised task of predicting the returns helps the policy to learn features?

**Comment by gebob19** [comment]
SF 2.0 sounds awesome! 

what would you include in the update? / any idea of when it might be released?

**Comment by alex-petrenko** [comment]
For now plans are relatively modest.
I want to make API more modular so that several types of online algorithms could be manifested.
Specifically, I want to add following use cases that are currently not supported:
1) Fully synchronous RL. It is not possible to configure SF to be completely on-policy right now. This is an important baseline many people requested
2) RL fully on GPU for environments such as Megaverse and Isaac Gym. There are codebases that can do that, but nothing that supports SF-style async learning. Matching/exceeding throughput and sample efficiency on Isaac Gym environments compared to SOTA algorithms would be my goal
3) Big refactoring to reduce code spaghetti. SF was originally created as an experimental codebase, proof-of-concept for async RL. I'm surprised and humbled at how many people started using it. Hopefully I can make code a bit easier to modify and maintain. Specifically, disentangle some of the components, move population-based training code out of the main classes.

I obviously have ideas beyond that, like adding support for transformer models and using Async RL ideas for MuZero-style algorithms, but that is further in the future. For the tasks above perhaps 2 months is somewhat realistic timeline.

**Comment by alex-petrenko** [comment]
@gebob19 btw any additional feedback is welcome!

**Comment by jarlva** [comment]
@alex-petrenko, just wondering if would make sense to consider muzero as part of the new major revision?
