### ISSUE TITLE
Question about CTDE

### ISSUE THREAD

**Issue by awarebayes** [alex-petrenko/sample-factory#126]
Hello, I have a question about centralized training and decentralized execution. Far as I understood it, this library uses something like Independent Asynchronous PPO and does not take into account all observations for critic evaluation.

Is this assumption correct? How difficult will it be to implement something like MAPPO (assuming current design perspective)?

I have observed, it works well with self play for doom environment, maybe because the agent cannot alter the environment that much.
I, for example, in order to encourage faster speeds, mitigate reward shaping, and introduce curriculum training, reformulate my single agent car racing game as a competitive RL, where two players compete, and first agent to come to the finish gets the reward. But agents from different teams do not see each other's observations, only their own screen(observation).

Do you think sample factory can be used in such setting?
Thanks in advance!

**Comment by alex-petrenko** [comment]
As far as I understand, you want agents to still make decisions based only on their own observations, but you want critic to learn based on both players' observations.

This can be accomplished by extending the observation space to contain both observations and using a custom actor-critic module. Sample Factory supports dictionary observations, so you can return {'self_obs': self_obs, 'other_obs': other_obs} from your step() function. If you look at Doom and DMLab envs, some of them return dictionaries of observations, so this should be fairly easy.

Then you need a custom actor-critic class that would have different architectures for actor (policy) and the critic. Here actor will only pay attention to self_obs, and critic will encode and use both self_ and other_obs. I don't think there's currently a way to use a custom actor critic module without modifying the code of Sample Factory (I plan to change this soon), but it should be a fairly easy code modification.

So overall, I'd say this is very easy to do.

What would be significantly harder is to train several different policies in parallel that all have the same critic (i.e. for collaborative tasks). This is because currently there is one critic for every policy. Learning one critic shared among many policies would require chagning policy_worker and learner substantially.

**Comment by awarebayes** [comment]
Yep, you are referring to Value Decomposition (VD) and centralized Q-learning by representing the joint Q-function as a function of each agent’s local Q-function. And it is going to be hard to implement. Writing it down, in case someone will use Github's search function :)
I will make a PR if I implement CTDE
Thanks for fast reply!
