### ISSUE TITLE
environment initialization 

### ISSUE THREAD

**Issue by cjmdd** [alex-petrenko/sample-factory#137]
I wonder why the environment initialization always fails when the number of agents exceeds 32. How can I solve it? 
The warnings are:"for split_idx, env_runner in enumerate(self.env_runners):
TypeError: 'NoneType' object is not iterable", then show " Waiting for 1 trajectory buffers..." continually.

**Comment by alex-petrenko** [comment]
This probably happens because the environment creation function returned None or crashed, which resulted in "env_runner" not being created (i.e. equal to None)

Can you either look through earlier logs to look for any other crashes or exceptions (as early in the log as possible), or consider attaching an sf_log.txt file from the experiment folder here, this will help us debug!

**Comment by cjmdd** [comment]
Dear alex-petrenko:
        My settings are" --quads_local_obs=12 --quads_num_agents=64  ", and my sf_log.txt is as follow:
[sf_log.txt](https://github.com/alex-petrenko/sample-factory/files/8810810/sf_log.txt)
Thanks for your help!

**Comment by cjmdd** [comment]
> Dear alex-petrenko: My settings are" --quads_local_obs=12 --quads_num_agents=64 ", and my sf_log.txt is as follow: [sf_log.txt](https://github.com/alex-petrenko/sample-factory/files/8810810/sf_log.txt) Thanks for your help!

**Comment by alex-petrenko** [comment]
The reason for this initialization failure is this:

`[2022-06-01 11:16:36,840][25445] Worker 1 is stuck or failed (120.592). Reset!`

In the main runner loop there is a timer and if the worker can't complete the initialization in some amount of time (by default 120 seconds), the system attempts to retry. If the initialization is actually that slow, it might make sense to try and increase the timeout `--reset_timeout_seconds=1000`

Otherwise, try to investigate why the environments take so long to initialize. Perhaps you're running in the cloud and the virtual machine is very slow at the start?

Another minor comment - since you have 48 CPU cores I'd suggest using either 24 or 48 workers rather than 36.

@Zhehui-Huang just to keep you in the loop, since this seems to be drone-related.
