### ISSUE TITLE
Reproducing Atari Results

### ISSUE THREAD

**Issue by mklissa** [alex-petrenko/sample-factory#270]
Hello,

first I wanted to say that this is a great codebase and I'm looking forward to use it more often to speed up RL experiments!
As a starting point I wanted to reproduce the results on Atari to get a sense of the moving parts. However, after a few runs on different games, I was only able to get very low episodic returns. I am sharing one of these runs that was logged on wandb: https://wandb.ai/martin-klissarov/sample_factory/groups/atari_breakout/workspace?workspace=user-martin-klissarov

I am mostly following the default parameters, but tried to replicate the exact setting of https://wandb.ai/wmfrank/atari-benchmark/reports/Atari-Sample-Factory2-Baselines-CleanRL--VmlldzoyMzEyNjIw

I am not exactly sure what might be causing this divergence. Any hints would be appreciated.

Cheers

**Comment by alex-petrenko** [comment]
Hi @mklissa 
Thank you for reporting this. 
From the looks of it, it might be there's something with the metrics reporting rather than the training itself.

Atari has this weird discrepancy between what the algorithm actually learns from (i.e. reward returned by env.step() function), and what everybody is reporting (some contents of the info dictionary, specifically `l` and `r` keys as far as I remember).

Can you try to run the enjoy script on your policy, maybe record a short video and post it here? It should be easy to do with the `enjoy` script. Then we will be able to tell if the policy is learning something, i.e. if the learning itself is broken or the metrics.

We have this special flag for atari to report additional metrics for Atari, i.e. policy_stats/avg_RecordEpisodeStatistics_reward. But

**Comment by mklissa** [comment]
Hello @alex-petrenko,

I think you are right, the video recorded shows score much higher (around 80 and sometimes 300). Here is an upload of the video: https://drive.google.com/file/d/1AV31kK3_LDHX5ApYSyX1DGfVuS3GC3Jr/view

It would be great to know how to fix the flags for Atari. I think you mention this at the end of your message, but it seems to have been cut short.

Cheers,
Martin

**Comment by alex-petrenko** [comment]
Sorry, not sure what happened there, must've pressed Enter accidentally :)

Disregard the early message about the flag. I was referring to `use_record_episode_statistics=True` which in the newest version isn't actually necessary because we added this function https://github.com/alex-petrenko/sample-factory/blob/c008165c34d65e93e8d261d2b3ebdf0989ccd6af/sample_factory/algo/sampling/sampling_utils.py#L63

It captures Atari's custom info["r"] rewards and reports them as `avg_RecordEpisodeStatistics_reward` in your Tensorboard or WandB. 

Now you might be wondering why you're seeing lower values, i.e. 70 instead of 300.
This is because we report FPS/frames after frameskip, i.e. multiplied by 4 for Atari. Mostly for historical and consistency reasons, it was customary at the time of development to report the number of env steps directly on x-axis, including the frameskipped.
Concidentally, I think ~70 is where SB3 is at 2.5M steps, so you should be good in terms of rewards.

To disable this you can use `--summaries_use_frameskip=False`, it will report FPS and steps on x-axis of plots in non-frameskipped env frames.

**Comment by alex-petrenko** [comment]
I think after this you will actually see that FPS is very similar to other frameworks, because the default configuration for atari (which you can find in atari_params.py) is very conservative and simply copies SB3/CleanRL's default config. The point of that exercise was simply to match the performance of other PPO implementations in identical settings.
This CFG currently uses very few workers, no double sampling, no async training, etc.

To unlock some of the SF2 power you can try:
```
        --summaries_use_frameskip=False
        --num_workers=16
        --num_envs_per_worker=8
        --worker_num_splits=2
        --train_for_env_steps=100000000
        --rollout=32
        --normalize_input=True
        --normalize_returns=True
        --serial_mode=False
        --async_rl=True
        --batch_size=1024
```

**Comment by alex-petrenko** [comment]
I started this run just now: https://wandb.ai/apetrenko/sf2_atari_breakout/reports/sf2-breakout-w16v8r32--Vmlldzo0MjM1MTQ4
With the following parameters:

```
--experiment=breakout_faster
--env=atari_breakout
--summaries_use_frameskip=False
--num_workers=16
--num_envs_per_worker=8
--worker_num_splits=2
--train_for_env_steps=100000000
--rollout=32
--normalize_input=True
--normalize_returns=True
--serial_mode=False
--async_rl=True
--batch_size=1024
--wandb_user=apetrenko
--wandb_project=sf2_atari_breakout
--wandb_group=breakout_w16v8r32
--with_wandb=True
```

Seems to be working pretty well so far. I'm sure you can find parameters that are much better than this still.

**Comment by mklissa** [comment]
Thank you for looking into this! That makes a lot of sense. I agree that Atari makes things a bit confusing with frame skipping. I think one of the way researchers differentiate between non-frameskipped frames and the frameskipped ones is to talk about Frames per Seconds versus Steps per Seconds, where 1 agent step = 4 game frames. Anyways, things are much clearer now.

However I am still wondering why the wandb report I get from running the code only goes up to an episodic return of 7-8 while the video clearly shows that the score goes up to at least 80. Is there something else I would need to configure to fix this reporting in wandb? Perhaps it has something to do with the `EpisodicLifeEnv` wrapper?

Thanks for trying a new run, but I unfortunately can't see it :O I think perhaps it has to be made public? Looking forward to trying it out with more workers and the really nice capabilities of SF2.

**Comment by alex-petrenko** [comment]
Sorry, this link to the run should work: https://api.wandb.ai/links/apetrenko/4ab5bjgh

The key is not to look at episodic reward as your main metric. What is typically reported as reward for Atari is just a different metric, in SF2 it is called `policy_stats/avg_RecordEpisodeStatistics_reward`

I vaguely remember this having something to do with reward shaping some Atari wrappers apply on top of raw env reward (because raw reward for some games has a weird scale like 10000, developers always used to apply some scaling, clipping, etc)

I also think that for RL purposes each life in Atari is considered a different episode, while in the actual ALE the game ends when you run out of lives.

All these tricks and hacks are "standard" in Atari, i.e. there's nothing special about how SF2 treats it, it has the exact same set of wrappers as CleanRL or SB3 for example. We just report metrics differently, i.e. "reward" is what the agent actually learns from and this RecordEpisodeStatistics_reward is a game score that people often report.

I hope this clears things.

P.S. I think in the `enjoy` script we actually print reward that comes from the wrapper, this would be equivalent to RecordEpisodeStatistics_reward. You can see this code here: https://github.com/alex-petrenko/sample-factory/blob/41235cd831281ac647a2988f593fec0c2a7ca8e5/sample_factory/enjoy.py#L209

**Comment by mklissa** [comment]
Oh okay I understand now, somehow I wasn't finding that statistic in the code but I see where it's happening. I guess it could be useful to have that `RecordEpisodeStatistics_reward ` statistic printed out during training as an easy way to sanity check a run (especially since on our compute cluster the compute nodes don't have access to internet). I guess I can follow the `enjoy` implementation to get that working.

Yes unfortunately Atari has all these domain specific heuristics to make things work, as many of the deep RL domains do at the moment.

The link you shared is working now, and yeah it clearly shows very good performance on Breakout. Also competitive with the CleanRL/SB3 results, even for a very different set of hyperparameters, which is interesting.

Thanks for working this out!
