### ISSUE TITLE
Running a trained agent raises: RuntimeError: view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by etale-cohomology** [alex-petrenko/sample-factory#36]
I managed to get this repo running on `python 3.8` (Ubuntu 18.04) without the `miniconda` environment by simply `pip install`ing the Python dependencies manually:

```
pip install torch
pip install psutil
pip install tensorboardX
pip install git+https://github.com/alex-petrenko/ViZDoom@doom_bot_project#egg=vizdoom
pip install faster-fifo
pip install opencv-python
pip install filelock
pip install threadpoolctl
```

Training runs as before, but running a trained agent (for example, via `python -m algorithms.appo.enjoy_appo --env=doom_battle --algo=APPO --experiment=doom_battle_w20_v20`) leads to the following error:

```
  File "/home/da/git/ai/sample-factory/algorithms/appo/model_utils.py", line 161, in forward
    x = x.view(-1, self.conv_head_out_size)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

One can fix this by going to `algorithms/appo/model_utils.py`, and, inside the `class ConvEncoder(EncoderBase):` class, inside the `def forward(self, obs_dict):` method, changing

```
x = x.view(-1, self.conv_head_out_size)
```

to 

```
x = x.contiguous().view(-1, self.conv_head_out_size)
```

**Comment by alex-petrenko** [comment]
Thank you for the suggestion!
I wonder why this tensor is not contiguous to begin with. Something probably changed between PyTorch versions.

Just calling contiguous() will copy the tensor which is additional overhead in both inference and learning. I'd like to know the reason why this tensor is not contiguous.

What happens if instead of installing the latest version of Pytorch you install the version that we were using? (1.4.0)

**Comment by alex-petrenko** [comment]
@etale-cohomology 
I could not see any measurable difference in performance in my current version, so I pushed your change to the repo
https://github.com/alex-petrenko/sample-factory/commit/638651de5fba205cb14ee71f80b125df8f33b978
I think this is because in my version tensors are actually contiguous (why wouldn't they be), so contiguous() just returns reference to the same tensor.
Thank you for suggesting this!

**Comment by etale-cohomology** [comment]
Following your idea, I installed PyTorch 1.4.0 (`pip install torch==1.4.0`) and `.contiguous()` was **not** needed.

Thanks for looking into this (and pushing the change).
