### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by neevparikh** [alex-petrenko/sample-factory#48]
Hi all,

As brought up in #47, I'm trying to get an async DQN with some of the Rainbow bells and whistles implemented with this framework. In familiarizing myself with the current setup, I had some questions about the intended ways to extend this.

* should each algorithm define it's own rollout/actor workers, learners, and policy workers? I imagine there is duplicated code this way, with the shared_buffer / thread management stuff. What are your recommendations on that front?
* do you guys have a contributing guide that I should read before starting?

**Comment by alex-petrenko** [comment]
I posted some comments in #47, please check those out!
I'd say the policy should be to reuse code wherever possible between algorithms, if it does not sacrifice performance. Otherwise, some amount of code duplication is fine, but should be kept to a minimum.

For off-policy algorithms, it makes sense to largely reuse the existing actor-worker-policy-worker infrastructure (you can call it a Sampler). Some modifications ought to be done, but they should be relatively minor. I expect actor-workers to be largely unaffected.

There is not a contributing guide, just please try to stick to the existing code style. Tests are welcome.
I can do code reviews to make sure you're on the right track.
Expect that some amount of refactoring will be needed. This is actually welcome, because SampleFactory is not very modular, as it is largely a one-person project and was not initially intended as a library of algorithms. But we're very excited to see people contributing other algorithms!

Performance-wise, the expectation is that off-policy algorithm will be as fast or faster than APPO, and the performance of APPO is unaffected. This is the main requirement for this contribution :)

**Comment by neevparikh** [comment]
Awesome thanks. I'm excited to work on this. Having algorithms that fully utilize single machines will be incredibly useful for all our projects at our lab.
