### ISSUE TITLE
[question] Validation results not good

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#90]
In gym classic-like env training, the model yields good results and completes the task.  Running enjoy with unseen data yields considerably lower results. 

. Added random noise to observations to prevent the model from memorizing (in training/validation). 
. Applied same normalization and also no normalization to training/validation. Same results. 

Any idea what it could be or what I can try? Is there something in the settings/switches worth trying? Your insight is greatly appreciated!

**Comment by alex-petrenko** [comment]
Oof sorry, I missed this.
Is this still a problem?
Training tensorboard shows average reward over last 100 episodes. Make sure this is not a statistical fluke.
also try parameter --continuous_actions_sample=False in enjoy script. This will deterministically choose the mean of the policy instead of sampling from the policy during evaluation. It might improve results on some envs.

Finally make sure you're executing from recent checkpoint, at the expected stage of training. Find checkpoint file in the train dir, the last part of the name indicates the number of samples at which this checkpoint was saved.

Use training with --save_every_sec=10 to checkpoint more often (if this is an issue)

**Comment by jarlva** [comment]
Yap, still is, going nutz trying to figure what is going on after 2 months...
I set to keep just one checkpoint model. Enjoy works well with training data. So I'm pretty sure it has the latest saved model.
It's as if the model memorized the training data. Despite adding +/- 1.5% random noise to the observations.
I'll try your suggestions.

**Comment by alex-petrenko** [comment]
Well, if you are hoping to achieve generalization to new unseen scenarios, this is not what RL is known for. So this might be a machine learning question, not SampleFactory question.
RL is notoriously good at memorizing training environments. You can find some thoughts on the generalization performance in this paper: https://arxiv.org/abs/1912.01588

Try to make your experience collection as diverse as possible, add as much data augmentation and randomization as you can.

**Comment by jarlva** [comment]
Just tried unsuccessfully "--continuous_actions_sample=False".
Yes, I'm aware. The unseen data is very similar to the training data. I'll try more randomization (limited with training data). Thanks for the tips! 

p.s. any news/plans to add MuZero?

**Comment by alex-petrenko** [comment]
Not before the RSS deadline :)

вт, 16 февр. 2021 г. в 00:34, jarlva <notifications@github.com>:
